D-01242 - log source chain usage
Holo-Host/holo-envoy pull request #129
Opened 2021-04-29 13:06 UTC by robbiecarlton

2021-05-03 14:06 UTC, timotree3 requested changes
Looks good but I have a single question/concern. Also should there be envoy tests for this?

2021-05-03 14:06 UTC, timotree3 commented on src/utils.ts
> +  ? './'
This seems sketchy. Why do we want to use the current directory in tests? In an e2e test it seems like we would want to get the actual database directory.

2021-05-05 08:45 UTC, alastairong commented
Merging latest `develop` so that we can human-test for meeting AC

2021-05-05 13:32 UTC, timotree3 approved these changes
It sounds like we're not testing this feature anyway so I retract my comment in favor of getting this PR merged.

2021-05-05 13:33 UTC, merged

2021-05-05 13:33 UTC, alastairong commented
Merged per discussion in stand up