Remove deactivate app
Holo-Host/holo-envoy pull request #152
Opened 2021-10-14 19:08 UTC by robbiecarlton

- [x] I have updated `CHANGELOG.md` to include all notable changes.
- [x] I have checked that `README.md` only contains up-to-date information.

2021-10-26 14:53 UTC, zo-el requested changes

2021-10-26 14:53 UTC, zo-el commented on tests/setup_conductor.js
> +    await mkdir(logDir, { recursive: true })
```suggestion
    await rmdir(logDir, { recursive: true })
    await mkdir(logDir, { recursive: true })
```

2021-10-26 14:53 UTC, zo-el commented on tests/setup_conductor.js
> +    await mkdir(logDir, { recursive: true })
you need to remove the old and then create a new one. 
And also this is not the best place to have the `mkdir`. 

It should be before spinning up `envoy`.

That will solve the need to `mkdir` in the shim

2021-10-26 21:29 UTC, timotree3 commented on tests/setup_conductor.js
> +    await mkdir(logDir, { recursive: true })
I wrote this code. I don't understand either of your comments. :upside_down_face: 

I don't see why we would need or want to remove the log dir. The logs get overridden automatically when new logs are created so removing the log dir wouldn't help anything, and in the future we may want to add timestamps to the log filenames so that they all remain there, which would mean that we need to keep the dir around.

This code can't be immediately before spinning up envoy because we are creating folders for holochain and lair to store things in. Envoy starts after lair. I originally put the `mkdir` for shim in this function, and it worked in the integration tests that use lair and holochain, but some of the tests spin up envoy directly without using either, so I needed to add the `mkdir` somewhere else in addition. I think the most direct and cleanest solution is to simply create the directory inside the `shimInit` function. It sounds like we're testing out that approach again because it should just work.

I guess since the current implementation of lair shim only connects to lair once holochain connects to it, it would be possible to have lair start after envoy, and then move these directories to envoy setup, but then you still have the problem that some of the tests don't use envoy setup, but instead call `shimInit` directly.

2021-10-27 08:29 UTC, zo-el commented on tests/setup_conductor.js
> +    await mkdir(logDir, { recursive: true })
1. Apologies, I did not mean to put this comment on the `logDir` but on `await mkdir(shim_dir, { recursive: true })`

2. In general I know what you are trying to do.

3. The point is that we have a working setup for all of this that is deployed and just because you have updated the test setup in this repo we should not need to update the actual src code of any critical part. And since the change was not tested, it's better to fix the test setup to include generation of the `shim-dir`(which replicates the currently deployed state in holo-nixpkgs), so that we don't have to release code we have not tested.

2021-10-27 13:01 UTC, timotree3 commented on tests/setup_conductor.js
> +    await mkdir(logDir, { recursive: true })
You do have a good point. Robbie and I were aware of this when re-making the change here. It just seemed better to manually test out the version with automatic creation of shim dir since it shouldn't cause any problems and results in better code quality in my opinion.

2021-10-27 13:21 UTC, zo-el commented on tests/setup_conductor.js
> +    await mkdir(logDir, { recursive: true })
Ideally, I would agree, but in this case, it is kinda deceiving because in production the shim-dir socket file is deleted and a check for the dir to exist is done by the holo-nixpkg service. This means this update is not really doing anything and is just used for dev testing, 

I am not going to push for it too much.
And hopefully, this does not have permission issues in production.

2021-10-27 13:21 UTC, zo-el approved these changes

2021-10-27 13:31 UTC, zo-el commented
Just update the ChangeLog everything else is good

2021-10-28 13:46 UTC, merged