Wormhole shim implementation
Holo-Host/holo-envoy pull request #40
Opened 2021-01-08 01:15 UTC by mjbrisebois

This is the shim solution from [DL-H0005](https://github.com/Holo-Host/rfcs/blob/master/teams/holo-hosting/decision_logs/DL-H0005-wormhole-updates-rsm.md)

2021-01-12 23:08 UTC, robbiecarlton requested changes
Couple of small changes, otherwise looks good.

2021-01-12 23:08 UTC, robbiecarlton commented on build/wormhole.js
> +		// throw new Error(`Got a null header`);
Remove comment

2021-01-12 23:08 UTC, robbiecarlton commented on tests/e2e/test_wormhole.js
> +    it("should process request and respond", async () => {
This test and the previous one have the same name. Can you give them different names?

2021-01-13 14:26 UTC, mjbrisebois commented on build/wormhole.js
> +		// throw new Error(`Got a null header`);
```suggestion
```

2021-01-13 15:12 UTC, robbiecarlton approved these changes

2021-01-13 15:13 UTC, merged