Rsm version tests
Holo-Host/holo-envoy pull request #41
Opened 2021-01-12 17:02 UTC by JettTech

2021-01-12 23:22 UTC, mjbrisebois requested changes
The tests cannot run due to the missing file so I have not reviewed the test file yet.  I'm having a hard time understanding what most of these changes are for.  There are a lot of changes but I don't see how it gets us closer to Envoy working with RSM.

2021-01-12 23:22 UTC, mjbrisebois commented on Makefile
> +HC_ADMIN_PORT	= 1234
Why `1234`?  This is less unique and more likely to conflict with other applications a developer could be running

2021-01-12 23:22 UTC, mjbrisebois commented on Makefile
> +	git clean-env -df ./docs
There is no `clean-env` git command

2021-01-12 23:22 UTC, mjbrisebois commented on Makefile
> +	npx-env chokidar -d 3000 'src/**/*.ts' -c "make --no-print-directory $*" 2> /dev/null
There is no `npx-env` command

2021-01-12 23:22 UTC, mjbrisebois commented on Makefile
> +clean-env-doc-envs:
Why does this need to be changed? `clean-docs` is clearer than `clean-env-doc-envs`

2021-01-12 23:22 UTC, mjbrisebois commented on Makefile
> +start-conductor:		$(HC_DIR)/pid
This is inconsistent with `make lair` and the make target is the thing you want to build, not a command you want to run.  So we should keep it as `make conductor`

2021-01-12 23:22 UTC, mjbrisebois commented on Makefile
> +	npx conductor-cli -q -p $(HC_ADMIN_PORT) gen-agent > $@ || rm $0
This change will break the `rm` command.  It worked as is.

2021-01-12 23:22 UTC, mjbrisebois commented on Makefile
> +	npx conductor-cli $(CCLI_OPTS) install-config -a "$$(cat $(AGENT))" $(CCLI_CONFIG)	|| true
What are we gaining from using a config?  From my perspective, we have more control by keeping the install commands separate like they are in `install-dnas`

2021-01-12 23:22 UTC, mjbrisebois commented on Makefile
> +clean-env: 			clear-env reset-hcc
We can remove `reset-hcc` because `stop-conductor` does what that command used to do.  It could cause unexpected issues to remove the databases directory while conductor is running.

2021-01-12 23:22 UTC, mjbrisebois commented on Makefile
> +	git clean-env -fdx
This is less clear and makes this repo different than all the other repos that have these same targets.

2021-01-12 23:22 UTC, mjbrisebois commented on tests/setup_conductor.js
> +	holochain			= ChildProcess.spawn( cmd, args, opts );
We are running conductor using make.  I think we eventually want to spin them up using node, but this takes a lot more code to do properly.  I don't see any code for handling graceful shutdowns here.

2021-01-12 23:22 UTC, mjbrisebois commented on tests/e2e/test_chaperone.js
> +const installedAppIds = yaml.safeLoad(fs.readFileSync('dna-config.yml'));
There is no `dna-config.yml` so the tests could not run.

2021-01-18 14:58 UTC, JettTech commented
Closing: The current decision is to complete the review of rsm updates to holo-envoy without including the rebase to the new dev environment, then to review and merge in the dev environment updates as a separate PR.

2021-01-18 14:58 UTC, closed without merging