B 03765 hosting bandwidth
Holo-Host/holo-envoy pull request #66
Opened 2021-02-17 05:02 UTC by JettTech

### Updates:
 - adds bandwidth calculation

2021-02-19 00:01 UTC, zo-el requested changes
I have left answers to the question and a question of the calculation.

2021-02-19 00:01 UTC, zo-el commented on src/index.ts
> +        // Note: we're calculating bandwidth by size of zomeCall_response in Bytes (not bits)
Can we calculate this over time? What are we trying to avoid (or benefits) by calculating bandwidth like this?

2021-02-19 00:01 UTC, zo-el commented on src/index.ts
> +    // QUESTION: We are currently not charing for app_info calls - should we be?
Yes, I think we should

2021-02-21 16:24 UTC, zo-el requested changes
What would it take to get bandwidth on `appInfo` calls? 
Why can't the work be done in this PR?

2021-02-22 22:44 UTC, zo-el approved these changes
LGTM

2021-02-23 17:04 UTC, JettTech commented
@zo-el - just to respond to the comments:
>What would it take to get bandwidth on appInfo calls?
>Why can't the work be done in this PR?

Basically, the appInfo calls are not being tracked at all in servicelogger.  If we wanted to update this, we'd have to also sign the payload, which would require updates to chaperone and envoy, and add the call to servicelogger.  Good idea, just would be a big scope creep for this ticket. :)

2021-02-23 17:05 UTC, merged

2021-02-23 20:26 UTC, JettTech commented on src/index.ts
> +        // Note: we're calculating bandwidth by size of zomeCall_response in Bytes (not bits)
I originally did, but since learned we are calculating only the volume of bandwidth for the call.